web:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./vantagecircle-web/:/var/www/html/
    - ./wordpress:/var/www/
    - ./conf/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
  extra_hosts:
    - "vantagecircle.local:127.0.0.1"
    - "server-test:159.89.166.228"
  links:
    - mysql

mysql:
    image: mariadb:10.3
    container_name: cms-db
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
    ports:
      - "3316:3306"
