
web:

  build: .

  ports:

    - "80:80"

    - "443:443"

  volumes:

    - ./vantagecircle-web/:/var/www/html/

    - ./wordpress:/var/www/

    - ./conf/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini

  extra_hosts:

    - "vantagecircle.local:127.0.0.1"

    - "server-test:159.89.166.228"

    - "mariadb:127.0.0.1"

  links:

    - mysql



mysql:

    image: mariadb:10.3

    container_name: mariadb

    volumes:

      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: name_db

    ports:

      - "3306:3306"
